create table "geral"."teste" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "geral"."teste" enable row level security;

CREATE UNIQUE INDEX teste_pkey ON geral.teste USING btree (id);

alter table "geral"."teste" add constraint "teste_pkey" PRIMARY KEY using index "teste_pkey";